[package]
name = "day_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library = { path = "../../library" }
priority-queue = "2.0.2"
